{{ if .Values.mongo.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.mongo.name }}
spec:
  type: {{ .Values.mongo.service.type }}
  {{- if .Values.mongo.service.ports }}
  ports:
    {{- toYaml .Values.mongo.service.ports | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.mongo.name }}
{{- end }}
