{{- if and .Values.postgres.enabled .Values.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.pgadmin.name }}
spec:
  type: {{ .Values.mongoExpress.service.type }}
  {{ if .Values.pgadmin.service.ports }}
  ports:
    {{- toYaml .Values.pgadmin.service.ports | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.pgadmin.name }}
{{- end }}