{{- if and .Values.report.enabled .Values.backend.enabled .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.report.name }}
spec:
  type: {{ .Values.report.service.type }}
  {{- if .Values.report.service.ports }}
  ports:
    {{- toYaml .Values.report.service.ports | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.report.name }}
{{- end }}
